Enumerables, request to merge.
AlejandroNo4/Enumerables pull request #1
Opened 2020-12-11 03:07 UTC by AlejandroNo4

This project is part of the Microverse Ruby curriculum. The objective of this project was to recreate some enumerators that already are built-in Ruby.

The rebuilt enumerators are:

#each => #my_each
#each_with_index => #my_each_with_index
#select => #my_select
#all? => #my_all?
#any? => #my_any?
#none? => #my_none?
#count=> #my_count
#map> #my_map
#inject=> #my_inject

As an additional, you can find at the Miscellaneous part two other versions of #my_map, that can only accept either blocks or procs.

2020-12-11 04:19 UTC, ebeagusamuel requested changes
# Changes Required :recycle: 
#### Hello @AlejandroNo4,
You have made a good attempt at the project, however, there are still a lot of changes that you need to make.
We normally test each of your methods against the original ruby enumerable methods, passing several ranges of input and we expect that your methods should behave exactly like the original ruby enumerable methods. Your methods are falling almost all the test cases and that means they do not behave like the original ruby enumerable methods. Because your methods are failing a lot of the test cases (almost 50 failed test) I won't be able to highlight all the changes you need to make, however, I will try as much as possible to help you understand why some of them are failing and I also suggest that you visit the official ruby docs and study those enumerable methods that you are asked to create and understand how they work. This will help you understand what you need to do and how you need to build your own enumerable methods.
- [ ] Please instead of having commented code in your script.rb, I suggest you move them into a separate file and import your enumerable into that file and you can test your method out as you wish there.
- [ ] Please check my comment below

#### Request another review when you are done making the needed changes.

slack(@ebeagusamuel)

2020-12-11 04:19 UTC, ebeagusamuel commented on script.rb
> +  end
- [ ] your method should return self after calling yield for each element in the self. That is how the original each method behaves but yours does not return `self`. Your my_each method should be able to work on an array, range, and hash just like the original each method. The best way to make sure your method works like the original method is to test it out against the original method.
`[1, 2, 3, 4, 5].my_each {|v| p v * 2}` should behave exactly as  `[1, 2, 3, 4, 5].each {|v| p v * 2}`
This should apply for when self is a range or hash.

2020-12-11 04:19 UTC, ebeagusamuel commented on script.rb
> +  end
- [ ] Same comment as that above

2020-12-11 04:19 UTC, ebeagusamuel commented on script.rb
> +  end
- [ ] my_select should return an array containing all elements of enum for which the given block returns a true value when self is an array or a range. Currently, my_select does not behave as it is expected. As stated above the best way to test your method is to test it against the original method and make sure they both have the same behavior.

2020-12-11 04:19 UTC, ebeagusamuel commented on script.rb
> +  end
- [ ] my_any?, my_all? and my_none? does not behave like their original enumerable methods. Again, study the original methods and make your own method behave exactly like the original methods behave.

2020-12-11 04:19 UTC, ebeagusamuel commented on script.rb
> +end
- [ ] Same comment as above. They all do not work as they are expected. study the original methods and implement yours to work exactly like the original.

2020-12-15 02:07 UTC, AlejandroNo4 commented
I did some changes at the last minute to the my_all? method. I had forgotten to do it before filling out the form.

2020-12-15 07:07 UTC, descholar-ceo requested changes
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @AlejandroNo4  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done. Just 4 test cases are remaining to implement and you will be ready to go.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] Fix the test case which are failing, inline in your codes

___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

2020-12-15 07:07 UTC, descholar-ceo commented on script.rb
> +  end
## 1. `#my_all?`
when a pattern other than Regex or a Class is given, `my_all?` should return true if all of the collection matches the pattern
example: 
```ruby
puts [3,3,3,3,3].my_all?(3) ==[3,3,3,3,3].all?(3) # => this should be true, but yours is giving false
```

2020-12-15 07:07 UTC, descholar-ceo commented on script.rb
> +  end
## 2. #my_any? 
when a pattern other than Regex or a Class is given, `my_any?` should return true if any of the collection matches the pattern

2020-12-15 07:07 UTC, descholar-ceo commented on script.rb
> +  end
## 3. #my_none?
 when a pattern other than Regex or a Class is given, `my_none?` should return false only if one of the collection matches the pattern

2020-12-15 07:07 UTC, descholar-ceo commented on script.rb
> +  end
## 4. `#my_map` should return an Enumerator if no block is given

2020-12-15 07:07 UTC, descholar-ceo commented on script.rb
> +puts multiply_els(a)
Remove this line of codes. It is for debugging purpose. You don't need to let it here

2020-12-16 01:47 UTC, acushlakoncept requested changes
# Status: Changes Required ♻️

### Great Job!, you're almost done here

You've done an awesome job so far 👌. Just one method left, bravo! 👏  
Let us quickly add some finishing touches and request another review.

- [ ] You are missing `#multiply_els` method, and it should accept an array as an argument and multiplies all the elements of the array together using `#my_inject` 
<img width="1008" alt="Screen Shot 2020-12-16 at 2 43 33 AM" src="https://user-images.githubusercontent.com/5264771/102294001-8bc3eb00-3f48-11eb-8804-0c0a6bdf9f07.png">
- [ ] [OPTIONAL] You are disabling a lot of rubocop error checks, line length can be fixed automatically using `rubocop -a` or `rubocop -A`

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-16 02:15 UTC, acushlakoncept approved these changes
# Status: PROJECT APPROVED  🎉 🚀

### Congratulations @AlejandroNo4, all your methods work fine 👏 

I will go ahead and mark this as complete, feel free to merge when you are ready. All the best with the next project.

### Cheers and Happy coding! 💻 👏

(Feel free to contact me on slack(@acushla), if you have any additional question)
Uduak Essien
[Twitter](https://twitter.com/acushlakoncept) | [LinkedIn](https://www.linkedin.com/in/acushlakoncept/)

2020-12-16 02:45 UTC, merged